name: 'dbt_flowgrid'
version: '1.0.0'
config-version: 2

profile: 'dbt_flowgrid'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
models:
  dbt_flowgrid:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    facts:
      +materialized: table
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
